WSN430 = ../../..

NAMES  = timerA-example

# common sources
SRC  = main.c
SRC += $(WSN430)/drivers/timerA.c
SRC += $(WSN430)/drivers/clock.c


INCLUDES  = -I. -I$(WSN430)/drivers/


-include $(WSN430)/drivers/Makefile.common

