WSN430 = ../../..

NAMES  = tsl2550-example


# common sources
SRC  = main.c
SRC += $(WSN430)/drivers/tsl2550.c
SRC += $(WSN430)/drivers/i2c0.c
SRC += $(WSN430)/drivers/uart0.c
SRC += $(WSN430)/drivers/clock.c


INCLUDES  = -I. -I$(WSN430)/drivers/


-include $(WSN430)/drivers/Makefile.common

