WSN430 = ../../..

NAMES  = ds1722-example


# common sources
SRC  = main.c
SRC += $(WSN430)/drivers/uart0.c
SRC += $(WSN430)/drivers/spi1.c
SRC += $(WSN430)/drivers/clock.c
SRC += $(WSN430)/drivers/ds1722.c


INCLUDES  = -I. -I$(WSN430)/drivers/


include $(WSN430)/drivers/Makefile.common

