# Setup paths to source code
# Support both development and tutorials configuration

WSN430 = ../../../../..

# define one name for each executable to be built
NAMES = ex1


SRC  = main.c
SRC += $(WSN430)/drivers/clock.c
SRC += $(WSN430)/drivers/timerA.c


INCLUDES  = -I. -I$(WSN430)/drivers

include $(WSN430)/drivers/Makefile.common
