CONTIKI = ../..

all: example-netflood #example-abc example-broadcast example-unicast example-polite example-trickle \
     #example-rucb example-runicast example-multihop example-announcement \
     #example-mesh

include $(CONTIKI)/Makefile.include
