CONTIKI = ../..

all: example-abc example-broadcast example-unicast example-polite example-trickle \
     example-rucb example-runicast example-multihop example-announcement
# example-rudolph0
# example-mesh example-collect \
#     example-rudolph1 example-rudolph2 \
#    


include $(CONTIKI)/Makefile.include
