WSN430 = ../../..

NAMES  = serial-example

# common sources
SRC  = main.c
SRC += $(WSN430)/drivers/uart0.c
SRC += $(WSN430)/drivers/clock.c

INCLUDES  = -I. -I$(WSN430)/drivers/


include $(WSN430)/drivers/Makefile.common

