WSN430 = ../../..

NAMES  = print_uids


# common sources
SRC  = main.c
SRC += $(WSN430)/drivers/uart0.c
SRC += $(WSN430)/drivers/clock.c
SRC += $(WSN430)/drivers/ds2411.c


INCLUDES  = -I. -I$(WSN430)/drivers/


include $(WSN430)/drivers/Makefile.common

