WSN430 = ../../..

NAMES  = cc1101-example


# common sources
SRC  = main.c
SRC += $(WSN430)/drivers/uart0.c
SRC += $(WSN430)/drivers/spi1.c
SRC += $(WSN430)/drivers/clock.c
SRC += $(WSN430)/drivers/cc1101.c


INCLUDES  = -I. -I$(WSN430)/drivers


include $(WSN430)/drivers/Makefile.common

