#ifndef TDMA_USERCONFIG_H_
#define TDMA_USERCONFIG_H_

#define MAX_PACKET_LENGTH 56
#define SLOT_COUNT 10
#define SLOT_TIME MS_TO_TICKS(10)
#define SLOT_GUARD_TIME 50
#define BEACON_LOSS_MAX 3

#endif
