WSN430 = ../..

# define one name for each executable to be built
NAMES  = firt_target second_target


# the specific sources files must be stored in a variable called SRC_target_name to be found automatically
# These variables can be undefined or empty

# sources files specific to 'first_target'
SRC_first_target  = main_first_target.c

# sources files specific to 'second_target'
SRC_second_target  = main_second_target.c
SRC_second_target += specific_file_for_second_target.c


# common sources for all targets
SRC  = $(WSN430)/drivers/cc2420.c
SRC += $(WSN430)/drivers/uart0.c
SRC += $(WSN430)/drivers/spi1.c
SRC += $(WSN430)/drivers/clock.c


INCLUDES  = -I. -I$(WSN430)/drivers/

# the makefile common will generate NAMES.hex and NAMES.elf files, and define 'all' and 'clean' directives
include $(WSN430)/drivers/Makefile.common

