# Setup paths to source code
# Support both development and tutorials configuration

WSN430 = ../../../..

NAMES = ex2

SRC  = main.c
SRC += $(WSN430)/drivers/clock.c
SRC += $(WSN430)/drivers/uart0.c
SRC += $(WSN430)/drivers/spi1.c
SRC += $(WSN430)/drivers/ds1722.c
SRC += $(WSN430)/drivers/i2c0.c
SRC += $(WSN430)/drivers/tsl2550.c


INCLUDES  = -I. -I$(WSN430)/drivers

include $(WSN430)/drivers/Makefile.common

