CONTIKI = ../..

all: example-abc example-unicast example-broadcast example-unicast \
     example-polite example-trickle example-rucb example-runicast \
     example-multihop example-announcement example-mesh \
     example-collect example-netflood



include $(CONTIKI)/Makefile.include
